### ISSUE TITLE
Quay handler of prescriptions-refresh fails to serialize YAML

### ISSUE THREAD

**Issue by fridex** [thoth-station/prescriptions-refresh-job#122]
**Describe the bug**

```
2022-02-28 20:05:53,471   1 CRITICAL root:105: Traceback (most recent call last):
  File "thoth-prescriptions-refresh", line 215, in <module>
    __name__ == "__main__" and cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "thoth-prescriptions-refresh", line 170, in quay_security
    handlers.quay_security(prescriptions)
  File "/opt/app-root/src/thoth/prescriptions_refresh/handlers/quay/security.py", line 260, in quay_security
    prescriptions.create_prescription(
  File "/opt/app-root/src/thoth/prescriptions_refresh/prescriptions.py", line 290, in create_prescription
    prescription_content = yaml.safe_load(content)
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/scanner.py", line 227, in fetch_more_tokens
    return self.fetch_alias()
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/scanner.py", line 610, in fetch_alias
    self.tokens.append(self.scan_anchor(AliasToken))
  File "/opt/app-root/lib64/python3.8/site-packages/yaml/scanner.py", line 922, in scan_anchor
    raise ScannerError("while scanning an %s" % name, start_mark,
yaml.scanner.ScannerError: while scanning an alias
  in "<unicode string>", line 20, column 1:
    * lz4: memory corruption due to  ... 
    ^
expected alphabetic or numeric character, but found ' '
  in "<unicode string>", line 20, column 2:
    * lz4: memory corruption due to a ... 

```

**To Reproduce**
1. See our stage environment

**Comment by fridex** [comment]
Maybe this is not happening with a more recent prescriptions-refresh code. Let's see and test.

**Comment by mayaCostantini** [comment]
Closing this issue as it seems to have been resolved given latest prescriptions.
/close
